name: Nivabit website CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Nivabit Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 38.242.149.11
          username: nivabit
          password: "@bigAnimalFarm24."

          script: |
            cd nivabit/public_html
            git pull
            npm install 
            npm run build
            pm2 reload nivabit

          # script: |
          #   cd nivabit/
          #   git pull
          #   npm install
          #   npm run build
          #   /home/nivabit/.nvm/versions/node/v20.17.0/bin/pm2  reload ${{ secrets.SERVICE_NAME }}
